<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Index</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <link rel="stylesheet" href="../../assets/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../../assets/styles/site.css" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="../index.html">Home</a>
      </div>
    </nav>
    <div class="container">
      <nav class="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="../index.html">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="./index.html">RxJS</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">ThrowError</li>
        </ol>
      </nav>

      <h1>ThrowError</h1>

      <section>
        <ul>
          <li>
            Creates an observable that immediately emits an error notification
          </li>
          <li>It does not emit any items</li>
          <li>
            Useful for testing error handling in observables by creating
            observables that always fail
          </li>
          <li>Often, it is more useful to use the JS <code>throw</code> statement</li>
        </ul>
      </section>

      <h2>Examples</h2>
      <section>
        <div>
          <ul>
            <li>This will return EMPTY values when the stream fails</li>
            <li>This will fix the broken stream by substituting and EMPTY observable</li>
          </ul>
          <div class="card">
            <div class="card-body">
              <code>
                this.http.get&lt;DataObject&gt;("http://mytargeturl").pipe(
                <br />
                catchError(() => EMPTY)
                <br />
                )
                <br />
              </code>
            </div>
          </div>
        </div>
        <div>
          This example catches an error, logs it to the console, then throws a new error
          <div class="card">
            <div class="card-body">
              <code>
                this.http.get&lt;DataObject&gt;("http://mytargeturl").pipe(
                <br />                
                catchError(err => { <br /> 
                  console.log(err); <br /> 
                  return throwError(() => new Error("could not retrieve")); <br /> 
                }) <br /> 
                <br />
                )
                <br />
              </code>
            </div>
          </div>
        </div>
        <div>
          Usually simpler to just use the JS throw function
          <div class="card">
            <div class="card-body">
              <code>
                this.http.get&lt;DataObject&gt;("http://mytargeturl").pipe(
                <br />                
                catchError(err => { <br /> 
                  console.log(err); <br /> 
                  throw new Error("could not retrieve"); <br /> 
                }) <br /> 
                <br />
                )
                <br />
              </code>
            </div>
          </div>
          <div>
            Another option is to set a property on the component to display an error message, then return EMPTY
            <div class="card">
              <div class="card-body">
                <code>
                  this.products$ = this.productService.getProducts().pipe(
                  <br />                
                  catchError(err => { <br /> 
                    this.errorMessage = err; <br /> 
                    return EMPTY; <br /> 
                  }) <br /> 
                  <br />
                  )
                  <br />
                </code>
              </div>
            </div>
        </div>
      </section>
    </div>
    <script src="../../assets/bootstrap/js/bootstrap.bundle.js"></script>
  </body>
</html>
